version: "3"
services:

  jenkins:
    build: .
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - devsecops-network
    volumes:
      - ./jenkins_vol:/jenkins
      
  sonarqube:
    image: sonarqube:7.9.2-community
    container_name: sonarqube
    ports:
      - 9000:9000
    networks:
      - devsecops-network
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - ./sonar_vol/conf:/opt/sonarqube/conf
      - ./sonar_vol/data:/opt/sonarqube/data
      - ./sonar_vol/extensions:/opt/sonarqube/extensions

  db:
    image: postgres:12.1
    container_name: postgres
    networks:
      - devsecops-network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./postgres_vol:/var/lib/postgresql
      - ./postgres_vol/data:/var/lib/postgresql/data
      
  nexus:
    image: sonatype/nexus3
    container_name: nexus3
    ports:
      - 8081:8081
    networks:
      - devsecops-network
    volumes:
      - ./nexus3_vol:/nexus-data
    
networks:
  devsecops-network:
    driver: bridge
